"""adding likes column

Revision ID: e181971ac099
Revises: 71a094cee2ee
Create Date: 2025-10-17 11:34:05.475525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e181971ac099'
down_revision = '71a094cee2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
